import React from "react"
import type { Metadata } from "next"
import "./globals.css"
import Sidebar from "@/components/Sidebar"

export const metadata : Metadata = {
  title : "Create Next App",
  description : "Generated by create next app"
}

export default function RootLayout({ children } : Readonly<{ children : React.ReactNode }>) {
  return (
    <html lang="en">
    {/*TODO*/}
    <body className="relative bg-blueGray-50 md:ml-64">
    <Sidebar/>
    <main className="min-h-screen w-full p-4 md:p-12">
      {children}
    </main>
    </body>
    </html>
  )
}
